spring.application.name=student

# ==============================
# Database
# ==============================
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/Student}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:1234}

# ==============================
# JPA / Hibernate
# ==============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.open-in-view=false

# ==============================
# Hikari Connection Pool
# ==============================
spring.datasource.hikari.maximum-pool-size=3
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.connection-timeout=20000

# ==============================
# Server
# ==============================
server.port=${PORT:8080}

# ==============================
# JWT
# ==============================
jwt.expiration=60000
refresh.token.expiration=600000

# ==============================
# Gemini
# ==============================
gemini.api.key=${GEMINI_API_KEY}

# ==============================
# Render Optimization
# ==============================
spring.main.lazy-initialization=true
server.tomcat.threads.max=20
server.tomcat.threads.min-spare=2